update scripts to guard against empty DB config values and update allowed-hosts to be more restrictive

diff --git a/haproxy-route-policy/snap/scripts/bin/gunicorn-start b/haproxy-route-policy/snap/scripts/bin/gunicorn-start
--- a/haproxy-route-policy/snap/scripts/bin/gunicorn-start
+++ b/haproxy-route-policy/snap/scripts/bin/gunicorn-start
@@ -29,5 +29,10 @@ if [ "$DJANGO_DEBUG" = "true" ]; then
   LOG_LEVEL="debug"
 fi
 
+if [ -z "$DJANGO_DATABASE_HOST" ] || [ -z "$DJANGO_DATABASE_PORT" ] || [ -z "$DJANGO_DATABASE_USER" ] || [ -z "$DJANGO_DATABASE_PASSWORD" ] || [ -z "$DJANGO_DATABASE_NAME" ]; then
+  >&2 echo "One or more database configuration values are missing. Please ensure database-host, database-port, database-user, database-password, and database-name are all set."
+  return 1
+fi
+
 exec gunicorn --bind 0.0.0.0:8080 haproxy_route_policy.wsgi \
   --capture-output --log-level="$LOG_LEVEL"
